
name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          npm run bootstrap
      - name: Lint
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build
